/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as ActRouteImport } from './routes/act'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiAirQualityRouteImport } from './routes/api/air-quality'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ActRoute = ActRouteImport.update({
  id: '/act',
  path: '/act',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAirQualityRoute = ApiAirQualityRouteImport.update({
  id: '/api/air-quality',
  path: '/api/air-quality',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/act': typeof ActRoute
  '/map': typeof MapRoute
  '/api/air-quality': typeof ApiAirQualityRoute
  '/api/events': typeof ApiEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/act': typeof ActRoute
  '/map': typeof MapRoute
  '/api/air-quality': typeof ApiAirQualityRoute
  '/api/events': typeof ApiEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/act': typeof ActRoute
  '/map': typeof MapRoute
  '/api/air-quality': typeof ApiAirQualityRoute
  '/api/events': typeof ApiEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/act' | '/map' | '/api/air-quality' | '/api/events'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/act' | '/map' | '/api/air-quality' | '/api/events'
  id: '__root__' | '/' | '/act' | '/map' | '/api/air-quality' | '/api/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActRoute: typeof ActRoute
  MapRoute: typeof MapRoute
  ApiAirQualityRoute: typeof ApiAirQualityRoute
  ApiEventsRoute: typeof ApiEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/act': {
      id: '/act'
      path: '/act'
      fullPath: '/act'
      preLoaderRoute: typeof ActRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/air-quality': {
      id: '/api/air-quality'
      path: '/api/air-quality'
      fullPath: '/api/air-quality'
      preLoaderRoute: typeof ApiAirQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActRoute: ActRoute,
  MapRoute: MapRoute,
  ApiAirQualityRoute: ApiAirQualityRoute,
  ApiEventsRoute: ApiEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
